name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ] 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Memberikan izin kepada 'bot' untuk menulis (push) ke branch gh-pages.
    permissions:
      contents: write
    # ===================================================

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          if [ -f "package.json" ]; then
            npm install
          fi

      - name: Test HTML
        run: |
          npm install -g html-validate
          html-validate index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ 
